### ISSUE TITLE
[Meta] Prospective Contents of Repo

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/repository.jurialmunkey#1]
Just to be clear, all that should go here in terms of your add-ons are Arctic Zephyr 2 and (maybe?) the Horizon icon pack? You don't want Aura or any of your other skins? I could potentially have the repo serve the correct respective versions of Aura to Krypton and Leia users, even 👍

**Comment by jurialmunkey** [comment]
Yeah just AZ2 and horizon icon pack. Eminence and Aura are on the official repo, so for any major revisions I generally just push them to the kodi repo. 

I'm currently only actively developing AZ2, so the other two don't get very frequent updates (though I will turn my attention to Aura2 once AZ2 is settled a bit - but when that happens, I will let you know).

**Comment by drinfernoo** [comment]
Sounds good 👍 I've pushed the initial version of the repo, but need you to [turn on GitHub Pages](https://help.github.com/en/articles/configuring-a-publishing-source-for-github-pages#enabling-github-pages-to-publish-your-site-from-master-or-gh-pages) for it to be accessible inside Kodi.

**Comment by drinfernoo** [comment]
I do believe I've got it working now, but I'll have to see if the repo works correctly inside Kodi once GitHub Pages is set up.

**Comment by jurialmunkey** [comment]
I've turned on github pages for master branch.

**Comment by drinfernoo** [comment]
Should be good to go! I've pushed the most recent tag to the repo this morning, 0.9.19-alpha5 with "Darker with Darker Dialogs" 👍

**Comment by jurialmunkey** [comment]
Excellent! I'll give it a spin now.

**Comment by jurialmunkey** [comment]
Looks good. I've added it to the first post of the thread. 
I'll leave it up to you to make a comment in the skin thread about it (or I can if you would prefer?)

**Comment by drinfernoo** [comment]
Go for it! It's your world, I'm just maintaining it 😂
