### ISSUE TITLE
[Meta] FYI - script.skinvariables is now an Arctic Horizon dependency.

### ISSUE THREAD

**Issue by jurialmunkey** [jurialmunkey/repository.jurialmunkey#10]
@drinfernoo - Just a heads-up for next time you update the repo that script.skinvariables is now a required dependency for Arctic Horizon, so it will need to be updated too (it's needed to build the viewtype visibility conditions).

Shouldn't need to be updated very often - but it will need to bump to v0.1.0 for AH.

**Comment by drinfernoo** [comment]
0.0.6 has been in for awhile 😉 But I'll update the repo with everything tomorrow.

**Comment by jurialmunkey** [comment]
Yeah I saw that -- it needs the new features in 0.1.1
Also, no rush at all! Just thought I'd give you the heads-up to avoid the otherwise inevitable questions about a missing dependency 😉

**Comment by jurialmunkey** [comment]
>  inevitable questions about a missing dependency 

Hahahaha, Oh dear! It appears that I jinxed you... 🤦

**Comment by drinfernoo** [comment]
@jurialmunkey I just forgot to switch back to the master branch (after experimenting with the matrix one) of the script before I updated the repo 😅

**Comment by drinfernoo** [comment]
@jurialmunkey Fixed 😅
