### ISSUE TITLE
xbmc.gui 5.14.0 dependency unmet

### ISSUE THREAD

**Issue by SWBZA** [jurialmunkey/repository.jurialmunkey#18]
Hi.

I've tried installing Arctic Zepher skin (tried all the versions I could find), but I get the XBMC.gui 5.14.0 dependency unmet error.  No google search has helped me and I'm stuck.  Any help in getting the skin installed?

Debian Linux, kodi version 19.0-RC1

Kind regards
Schalk

**Comment by jurialmunkey** [comment]
There is no Matrix version of Arctic Zephyr and the skin is no longer being developed. If you download the zip and change the gui version in addon.xml manually then you will probably be able to install it but there is no official support for AZ in Matrix.
