### ISSUE TITLE
Moviedbhelper not compatible with Matrix

### ISSUE THREAD

**Issue by khezuu** [jurialmunkey/repository.jurialmunkey#19]
When trying to install moviedbhelper from the 2.0 repository it fails due to incompatibility with matrix

error after installing:
http://paste.kodi.tv/culoyohoke

after kodi restart when the incompatibility message pops up:
http://paste.kodi.tv/meyugepalu

**Comment by JayDee696969** [comment]
> When trying to install moviedbhelper from the 2.0 repository it fails due to incompatibility with matrix
> 
> error after installing:
> http://paste.kodi.tv/culoyohoke
> 
> after kodi restart when the incompatibility message pops up:
> http://paste.kodi.tv/meyugepalu

You have to install the alpha reo for Matrix https://github.com/jurialmunkey/repository.jurialmunkey/tree/matrix

**Comment by drinfernoo** [comment]
No, you don't. The repository now serves both Leia and Matrix.
