### ISSUE TITLE
TMDbH freezes & crashes Matrix on Arch Linux

### ISSUE THREAD

**Issue by cgcgcgcgcg** [jurialmunkey/repository.jurialmunkey#20]
I tried a Kodi 19 build that used TMDbH widggets on some menus, and every time I scrolled to those menus, or opened TMDbH it froze Kodi, and crashed it.
So I installed just TMDbH on an empty Matrix, same thing happens, pic (after showing that for a few seconds, Kodi is closed) and log below.
https://pastebin.com/KmTbUVri
Another log with with debug logging enabled:
https://pastebin.com/h1hhW9vi
![ksnip_20210223-203517](https://user-images.githubusercontent.com/38960370/108891612-97522300-7617-11eb-9d06-1830ca9f3f67.png)

**Comment by jurialmunkey** [comment]
Thanks for the report but this page is for the repository. Can you open the issue on the correct github page for TMDbH at:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues

**Comment by cgcgcgcgcg** [comment]
> Thanks for the report but this page is for the repository. Can you open the issue on the correct github page for TMDbH at:
> https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues

I'm sorry, it happened due to speed, posted in the proper place just now.
