### ISSUE TITLE
[Meta] Updating branches in github repos

### ISSUE THREAD

**Issue by jurialmunkey** [jurialmunkey/repository.jurialmunkey#21]
@drinfernoo - A heads-up that I'm updating the branches in TMDbH, Arctic Horizon, and SkinVariables so that they will now have separate `leia` and `matrix` branches. The `master` branch will no longer be leia and is being stripped back to just a Readme.

I've updated TMDbH in this way, and will do so shortly for AH and SV.

EDIT: And now updated for AH and SV too (and also context menu addon for TMDbH). Also, I think AH should be good to upload to the repo for Matrix -- there's still a few minor changes to add in new Matrix features but there were barely any necessary/required changes so it was really quick to get a working version up.

**Comment by drinfernoo** [comment]
Done 🎉 I've updated all the submodules and pushed the relevant add-ons to their relevant branches :+1:
