### ISSUE TITLE
Update failed error

### ISSUE THREAD

**Issue by jaimsitecom** [jurialmunkey/repository.jurialmunkey#22]
Been trying to update from 4.3.9 to the latest 4.3.10 via juriel repo but keeps on getting update fail (invalid package). 

Hope it gets fixed. Ty

**Comment by kolekan** [comment]
The  https://github.com/jurialmunkey/repository.jurialmunkey/blob/master/matrix/zips/plugin.video.themoviedb.helper/plugin.video.themoviedb.helper-4.3.10.zip
is an empty zip file. Please fix it.

**Comment by xyzfre** [comment]
I'm having the same issue I get a update error when trying to update to the new version￼

**Comment by drinfernoo** [comment]
Looks like a corrupted file got pushed. I'll try to fix it today.

**Comment by drinfernoo** [comment]
I've just pushed a fixed zip.

**Comment by xyzfre** [comment]
Thank you for the fix and all the hard work update went through with no issues￼
