### ISSUE TITLE
Context menu add-on not compatible

### ISSUE THREAD

**Issue by KishenG** [jurialmunkey/repository.jurialmunkey#24]
I keep getting errors when trying to install the additional context menus. I can sometimes manually force it to install but it gets disabled by Kodi when I restart.

**Comment by drinfernoo** [comment]
If you're getting errors, then wouldn't it make sense to show what the errors are?

In either case, if this is still an issue, re-open it at https://github.com/jurialmunkey/context.themoviedb.helper/issues/.
