### ISSUE TITLE
TMDB Helper-All Playlists not showing when assigning to Widget

### ISSUE THREAD

**Issue by cgtjr1** [jurialmunkey/repository.jurialmunkey#25]
Hey there,
  I am having an issue with a new setup. After I install TMDB Helper and sync my trakt lists, it creates the playlists of my trakt lists. they work properly and are all there, but when I go to set up my widgets and go into the playlists thru the skin settings it only shows 5 of the 12 playlists. I have wiped and done a complete fresh install and it is still happening. It work fine on my main setup, this is a secondary setup (for my dad). We have everything the same except for one. Our local (external HDD) files are different. I have a Movies folder containing all files and a TV one the same way. He has a Movie folder with subfolders by genre and those contain the files. I don't know if this contributes or not but it's the only difference.  It has all the files in the playlists it creates...I just can't see them when doing the widget set up.  We both are running Matrix on the same model of Nvidia Shield.

**Comment by drinfernoo** [comment]
This sounds more like a skin issue, if anything. If it's creating the playlists, then you should be able to find them when doing widget setup.

Either way, I'd consider re-opening this issue at https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues/, as that's the proper repository for TMDbHelper.
