### ISSUE TITLE
Widget Artwork Issue

### ISSUE THREAD

**Issue by JC253** [jurialmunkey/repository.jurialmunkey#26]
Hello Jurialmunkey, firstly thank you for all you do. Love all of your work.

I've been having an issue for the last 3 days now regarding widget artwork. It seems like whenever I have fanart.tv settings enabled, some widget items won't display artwork at all (see picture.) I've tried deleting TMDB and Fanart Database items, I've uninstalled and reinstalled TMDbH, I've removed the Thumbnails folder several times, I've ran wizard cleaners & keep running into the same problem. I've used these settings for a while now without issue up until 3 days ago. I thought it would just resolve itself after a day or two, but figured I'd ask now that I'm still seeing the problem on day 3. Idk if it's even anything on your end that you could fix, just wanted to mention it in case you can. First pic is issue I'm having. Second pic is settings I've used. Thanks for everything.

![Screenshot (211)](https://user-images.githubusercontent.com/79684237/135118086-b0a35809-b743-446e-9d9b-d5845a40a7a9.png)

![Screenshot (212)](https://user-images.githubusercontent.com/79684237/135118145-095ca930-dd6e-49b4-b29a-6f10f17259ed.png)

**Comment by JC253** [comment]
Sorry, I accidently clicked on 'close' so I re-opened.

**Comment by jurialmunkey** [comment]
Can you open this as an issue on the tmdbhelper github: https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues

(you're currently on the github for my repository not tmdbhelper)

**Comment by jurialmunkey** [comment]
Also it looks like you've disabled fanart TV for widget artwork but are using a widget...
