### ISSUE TITLE
Arctic Horizon skin on Kodi

### ISSUE THREAD

**Issue by Ggghhhghhghghhgg** [jurialmunkey/repository.jurialmunkey#28]
Hello again @drinfernoo. This isn't an issue or anything, but I was just wondering how do you make the Arctic Horizon skin look like this?

![Lhk5Xqj](https://user-images.githubusercontent.com/93388628/140331479-6407583e-a2f9-442a-9747-040e3ca49940.jpg)

**Comment by drinfernoo** [comment]
That is a "Fullscreen Widget".
