### ISSUE TITLE
The Movie Db Helper.

### ISSUE THREAD

**Issue by Greg0580** [jurialmunkey/repository.jurialmunkey#33]
I Need Your Help Please .
i install your Repo and all going Well Except When I open it .and the bottom of the page is MDbList when i press on it one them is call Your Lists when i press on it . It wont Open The CogWheel  Spins A Couple Of times and stops . I have Tmdb,imdb,Mdblist, But it still Wont Open. As i said everthing else works everything else in the same menu opens and plays .

                                              Thank You. Greg.

**Comment by jurialmunkey** [comment]
You need a personal api key for mdblist.

**Comment by Greg0580** [comment]
Yes I have Api key/both MDblist API Key and OMDb API Key both have Been Activated.  
Thank.  You.

**Comment by jurialmunkey** [comment]
Please open issues on tmdbhelper github
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/issues
