### ISSUE TITLE
Repository inaccessible

### ISSUE THREAD

**Issue by KennLDN** [jurialmunkey/repository.jurialmunkey#37]
Using the listed repository link, `https://jurialmunkey.github.io/repository.jurialmunkey/`, and installing the repository zip then trying to enter the repo, I am met with "Could not connect to repository". 

Tried both Matrix and Nexus, all other repositories are fine.

**Comment by RaraCool** [comment]
Vouch, I'm on Kodi Matrix on OSMC version 2022.10-1. Encountering the exact same issue.

**Comment by jurialmunkey** [comment]
Yes I'm aware of the issue.

**Comment by jurialmunkey** [comment]
Please use v2.2 of the repository for the time being
https://github.com/jurialmunkey/repository.jurialmunkey/blob/master/repository.jurialmunkey-2.2.zip?raw=true

**Comment by RaraCool** [comment]
Checked back on the current repository and it's now working. Keep up the great work 🙏
