### ISSUE TITLE
Tmdb helper 5.1.0-nexus

### ISSUE THREAD

**Issue by Greg0580** [jurialmunkey/repository.jurialmunkey#38]
Hello 
Thank you for Great addon.
I see in the latest updates 5.1.0-nexus  you added Info Tagger. 0.0.5.
I was wondering what the update for  tmdb helper Changelog are. What's  new etc and what this Info Tagger is about as there no Changelog  for both of them 
I was wondering if you could add Changelogs in the information above  the uninstall/auto update are. And for tmdb helper the same or add Changelog under settings in tmdb helper please.  These only suggestions. I have read on different sites some people would like this added to tmdb helper. 
Thank you for all your time and effort I much appreciate it  👍

**Comment by jurialmunkey** [comment]
Infotagger is a module dependency. It is used for some internal Kodi functions. It doesn't concern end users.

You can read release notes in the TMDbHelper releases page:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/releases

Every release contains a changelog diff which allows you to see the commit history
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/compare/v5.0.54...v5.1.0

**Comment by Greg0580** [comment]
Thank you.  For your quick reply and Good information  and time.  Much Appreciated Thank you.  👍



Sent from my Galaxy



-------- Original message --------
From: jurialmunkey ***@***.***>
Date: 23/02/23 00:19 (GMT+12:00)
To: "jurialmunkey/repository.jurialmunkey" ***@***.***>
Cc: Greg0580 ***@***.***>, Author ***@***.***>
Subject: Re: [jurialmunkey/repository.jurialmunkey] Tmdb helper 5.1.0-nexus (Issue #38)


Infotagger is a module dependency. It is used for some internal Kodi functions. It doesn't concern end users.

You can read release notes in the TMDbHelper releases page:
https://github.com/jurialmunkey/plugin.video.themoviedb.helper/releases

Every release contains a changelog diff which allows you to see the commit history
***@***.***<https://github.com/jurialmunkey/plugin.video.themoviedb.helper/compare/v5.0.54...v5.1.0>
