### ISSUE TITLE
Repo have wrong dependencies for Matrix while installing Arctic Horizon 2

### ISSUE THREAD

**Issue by slmlm2009** [jurialmunkey/repository.jurialmunkey#39]
Hi

I used last version of repo which is obviously from the code has seperate files for Matrix setups. However while installing Arctic Horizon 2 on my Matrix build I recieve the infamous xbmc.python 3.0.1 can't be satisfied which is only available for kodi nexsus.

Looking for your help to sort it out.

Much love and thanks

**Comment by jurialmunkey** [comment]
I don't support Matrix anymore. The current version of the skin requires a higher version of TMDbHelper than is available for Matrix.
