### ISSUE TITLE
Update to v0.9.33 Alpha 7

### ISSUE THREAD

**Issue by jurialmunkey** [jurialmunkey/repository.jurialmunkey#4]
@drinfernoo - looks like repo is only on 0.9.33-a1 but latest is 0.9.33-a7
Can you update? :)

**Comment by drinfernoo** [comment]
Whoops! I'll get it up there soon!

**Comment by drinfernoo** [comment]
Not sure how long it was out of date... my bad 😆 Fixed now 👍
