### ISSUE TITLE
repo update v 3.4 broken in omega

### ISSUE THREAD

**Issue by Liquidrag** [jurialmunkey/repository.jurialmunkey#42]
tried a fresh install but omega cannot connect to the repo

zip installs correctly in both nexus and omega but theres a connection error in omega.

https://jurialmunkey.github.io/repository.jurialmunkey/

**Comment by AakashC2020** [comment]
Hi @jurialmunkey,

Yes, like @Liquidrag has said, I'm unable to update both the Skin Variables and Arctic Fuse add-ons after the repo got updated today. Kindly check and resolve.

**Comment by JaySmoka187** [comment]
Hello
I have the same problem.
[kodi.log](https://github.com/jurialmunkey/repository.jurialmunkey/files/13604765/kodi.log)

**Comment by jurialmunkey** [comment]
https://github.com/jurialmunkey/repository.jurialmunkey/raw/master/repository.jurialmunkey-3.3.zip

**Comment by jurialmunkey** [comment]
Looks like server cache has refreshed. Should be working now from 3.4 as long as you're on a nightly / Beta 2 (if you're still on Beta 1 either upgrade Kodi version or downgrade repo version to 3.3).

I've repushed SV and AF with a version bump to help them update in case they are stuck for whatever reason.

**Comment by AakashC2020** [comment]
> https://github.com/jurialmunkey/repository.jurialmunkey/raw/master/repository.jurialmunkey-3.3.zip

Thank you @jurialmunkey !
