### ISSUE TITLE
[Meta] Repository Name Change

### ISSUE THREAD

**Issue by drinfernoo** [jurialmunkey/repository.jurialmunkey#7]
For convenience, would it make a difference to you if this repository was renamed to `jurialmunkey.github.io`?

It would make the file source simpler: https://jurialmunkey.github.io/

**Comment by jurialmunkey** [comment]
It doesn't matter to me but how would that affect people with the repository already installed?

**Comment by drinfernoo** [comment]
Oh, I guess you're right. As an alternative, if you were to build GitHub Pages from a *new* repo named "jurialmunkey.github.io", and we can just put the repo zip there for easy installation?

**Comment by drinfernoo** [comment]
For what it's worth, it occurred to me that changing the name of *this* repo shouldn't make a difference, as GitHub *should* redirect to the "new" one.

**Comment by jurialmunkey** [comment]
Yeah fine if you want to change the name. Let me know if I need to do anything.

**Comment by SerpentDrago** [comment]
Create a new github repo .  name it  jurialmunkey.github.io

move the 

index.html and  repository.jurialmunkey-1.2.zip files 

to that new github repo 

and enable github pages on it .

now people only need to use  http://jurialmunkey.github.io/  as the kodi filesource to find and install the repo zip .

**Comment by drinfernoo** [comment]
@jurialmunkey That would be sweet! By having a new repository named `jurialmunkey.github.io`, we can simply drop the repo zips in there, and benefit from a shorter URL, without the hassle of migrating the repo to a new address.

**Comment by jurialmunkey** [comment]
Done

So if I'm understanding correctly - the one I just created at https://jurialmunkey.github.io/ is only used by users as the initial file manager source to install the repo zips, but all the actual repo stuff stays here in the current one.

**Comment by drinfernoo** [comment]
Yep, the source appears to be working 👍

I'm not seeing the matrix zip *in* Matrix, though 🤔 I'm not sure why that would be...

**Comment by drinfernoo** [comment]
This was fixed by https://github.com/jurialmunkey/repository.jurialmunkey/pull/15.
